### ISSUE TITLE
is the lstm2d the true mdlstm ?

### ISSUE THREAD

**Issue by Duum** [johnsmithm/handwritten-tf-1.0#2]
I see you have changed the mdlstm to lstm2d, but I think the lstm2d implemented by tensorflow does not consider the both dimension as introduced by Alex Graves. Have you tested its accuracy?

**Comment by johnsmithm** [comment]
both has the accurancy about 15% label rate error, but lstm2d is faster because in the mdlstm tf.while_loop has parallel_iterations=1. lstm2d still has the information from both dimensions, but the information from another dimenstion is input, but not passed through a gate as in the original multidimentional lstm

**Comment by Duum** [comment]
Do you have the interest to implement this 

> Joint Line Segmentation and Transcription for End-to-End Handwritten Paragraph Recognition[](https://arxiv.org/abs/1604.08352)
?

**Comment by johnsmithm** [comment]
It is interesting

**Comment by Duum** [comment]
I have complete a version, but it not works well. If you want to implement it, I'm willing to help.

**Comment by johnsmithm** [comment]
close for non activity
